#!/bin/bash
begin="^\[[[:space:]]*[0-9]*\.?[0-9]*\] "
warn="\(WW\)"
info="\(II\)"
cat /var/log/anaconda/X.log | grep -E "$begin$warn" | sed -E "s/$warn/Warning:/" > full.log
cat /var/log/anaconda/X.log | grep -E "$begin$info" | sed -E "s/$info/Information:/" >> full.log
